kind: pipeline
name: Signature Drone

steps:
 - name: compile
   image: fajar4561/aosp-builder:latest
   environment:
     TG_CHAT_ID:
       from_secret: TG_CHAT_ID
     TG_TOKEN:
       from_secret: TG_TOKEN
     AWAL:
       from_secret: AWAL
     AKHIR:
       from_secret: AKHIR
   commands:
      - git config --global user.name "$AWAL"
      - git config --global user.email "abenkenari@gmail.com"
      - git clone --depth=1 https://$AWAL:$AKHIR@github.com/Kneba/Ruega-Kernel-X00T -b 44 kernel && cd kernel
      - curl https://raw.githubusercontent.com/Kneba/kernel_builder_drone/nlvv/build.sh > run.sh
      - bash run.sh
